"""add reader table and foreign key to book one to many

Revision ID: 855afbb22946
Revises: 0919d9efd5ea
Create Date: 2024-09-11 20:49:56.478806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855afbb22946'
down_revision = '0919d9efd5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reader_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'readers', ['reader_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reader_id')

    op.drop_table('readers')
    # ### end Alembic commands ###
